describe('sequentially run tests', () => {
    require('./routes/businesses.test')()
    require('./routes/resource.test')()
    require('./routes/settings.test')()
    require('./routes/sites.test')()
    require('./routes/contract.test')()
    require('./routes/contractPeriod.test')()
    require('./routes/contractPricing.test')()
    require('./routes/location.test')()
    require('./routes/caseImpact.test')()
    // require('./routes/caseCashflow.test')()
    // require('./routes/opportunity.test')()
    // require('./routes/project.test')()
    // require('./routes/cashflow.test')()
    // require('./routes/impact.test')()
    require('./routes/flow.test')()
    require('./routes/flowImpact.test')()
    require('./routes/unit.test')()
    require('./routes/group.test')()
    require('./routes/groupTag.test')()
    require('./routes/mac.test')()
    require('./routes/metric.test')()
    require('./routes/metricValue.test')()
    require('./routes/asset.test')()
    require('./routes/meter.test')()
    require('./routes/assetMeter.test')()
    require('./routes/task.test')()
    require('./routes/report.test')()
})